name: quick_food_delivery
description: A quick food and grocery delivery app.
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # For fetching web images
  provider: ^6.1.1 # For state management (cart)
  intl: ^0.19.0 # For currency formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_default.png # A placeholder image if web image fails
